In [ ]:
# Exercise 1: Calculate the multiplication and sum of two numbers

num1 = int(input("number 1: "))
num2 = int(input("number 2: "))

product = num1 * num2

if product <= 1000:
  print(product)
else:
  print(num1 + num2)

number 1: 30
number 2: 40
70

In [ ]:
# Exercise 2: Print the Sum of a Current Number and a Previous number

print("Printing current and previous number and their sum in a range(10)")
previous_num = 0

for i in range(1, 11):
    x_sum = previous_num + i
    print("Current Number", i, "Previous Number ", previous_num, " Sum: ", x_sum)
    previous_num = i

Printing current and previous number and their sum in a range(10)
Current Number 1 Previous Number  0  Sum:  1
Current Number 2 Previous Number  1  Sum:  3
Current Number 3 Previous Number  2  Sum:  5
Current Number 4 Previous Number  3  Sum:  7
Current Number 5 Previous Number  4  Sum:  9
Current Number 6 Previous Number  5  Sum:  11
Current Number 7 Previous Number  6  Sum:  13
Current Number 8 Previous Number  7  Sum:  15
Current Number 9 Previous Number  8  Sum:  17
Current Number 10 Previous Number  9  Sum:  19

In [ ]:
# Exercise 3: Print characters present at an even index number

string = input("enter string: ")

print(f"original string is {string}")
print(f"printing only even index chars")

for i in range(len(string)):
  if i % 2 == 0:
    print(string[i])

enter string: PYnative
original string is PYnative
printing only even index chars
P
n
t
v

In [ ]:
# Exercise 4: Remove first n characters from a string

def remove_chars(word, n):
    return word[n:]

print("Removing characters from a string")
print(remove_chars("pynative", 4))
# output 'tive' first four characters are removed

print(remove_chars("pynative", 2))
# output 'native'

Removing characters from a string
tive
native

In [ ]:
# Exercise 5: Check if the first and last numbers of a list are the same

lst1 = [10, 20, 30, 40, 10]
# output True

lst2 = [75, 65, 35, 75, 30]
# Output False

def check_lst(lst):
  if lst[0] == lst[-1]:
    return True
  else:
    return False

print(check_lst(lst1))
print(check_lst(lst2))

In [ ]:
# Exercise 6: Display numbers divisible by 5

lst = [10, 20, 33, 46, 55]

for i in lst:
  if i % 5 == 0:
    print(i)

10
20
55

In [ ]:
# Exercise 7: Find the number of occurrences of a substring in a string

string = "Emma is good developer. Emma is a writer"
word = "Emma"

count = 0
for i in string.split():
  if i == word:
    count += 1

print(f"{word} appeared {count} times")

Emma appeared 2 times

In [ ]:
# Exercise 8: Print the pattern

for i in range(1,6):
  print(str(i) * i)

1
22
333
4444
55555

In [ ]:
# Exercise 9: Check Palindrome Number

def check_num(number):
  num = str(number)
  if num == num[::-1]:
    return True
  else:
    return False

print(check_num(245))
print(check_num(242))

False
True

In [ ]:
# Exercise 10: Merge two lists using the following condition
# odd numbers from the first list and even numbers from the second list.

lst1 = [10, 20, 25, 30, 35]
lst2 = [40, 45, 60, 75, 90]

res = []

for i in lst1:
  if i % 2 != 0:
    res.append(i)

for j in lst2:
  if j % 2 == 0:
    res.append(j)

print(res)

[25, 35, 40, 60, 90]

In [ ]:
# Exercise 11: Get each digit from a number in the reverse order.

num = input("enter the number: ")

ls = list(reversed([num[i] for i in range(len(num))]))

print(*ls)

enter the number: 78965
5 6 9 8 7

In [ ]:
# Exercise 12: Calculate income tax

income = 45000
tax_payable = 0
print("Given income", income)

if income <= 10000:
    tax_payable = 0
elif income <= 20000:
    x = income - 10000
    tax_payable = x * 10 / 100
else:
    tax_payable = 0
    tax_payable = 10000 * 10 / 100
    tax_payable += (income - 20000) * 20 / 100

print("Total tax to pay is", tax_payable)

Given income 45000
Total tax to pay is 6000.0

In [ ]:
# Exercise 13: Print multiplication table from 1 to 10

for i in range(1, 11):
    for j in range(1, 11):
        print(i * j, end=" ")
    print("\t\t")

1 2 3 4 5 6 7 8 9 10
2 4 6 8 10 12 14 16 18 20
3 6 9 12 15 18 21 24 27 30
4 8 12 16 20 24 28 32 36 40
5 10 15 20 25 30 35 40 45 50
6 12 18 24 30 36 42 48 54 60
7 14 21 28 35 42 49 56 63 70
8 16 24 32 40 48 56 64 72 80
9 18 27 36 45 54 63 72 81 90
10 20 30 40 50 60 70 80 90 100

In [ ]:
# Exercise 14: Print a downward half-pyramid pattern of stars

for i in range(6, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print(" ")

* * * * *
* * * *
* * *
* *
*

In [1]:
# Exercise 15: Get an int value of base raises to the power of exponent

def exponent(base, exp):
  print(f"{base} raises to the power of {exp}: {base ** exp} i.e.")

exponent(2, 5)
exponent(7, 8)

2 raises to the power of 5: 32 i.e.
7 raises to the power of 8: 5764801 i.e.

In [2]:
# Exercise 16: Check Palindrome Number

def check_num(number):
  num = str(number)
  if num == num[::-1]:
    return True
  else:
    return False

print(check_num(245))
print(check_num(242))

False
True

In [5]:
# Exercise 17: Generate Fibonacci series up to 15 terms

num1, num2 = 0, 1

print("Fibonacci sequence:")
for i in range(15):
    print(num1, end="  ")
    res = num1 + num2

    num1 = num2
    num2 = res

Fibonacci sequence:
0  1  1  2  3  5  8  13  21  34  55  89  144  233  377

In [6]:
# Exercise 18: Check if a given year is a leap year

def is_leap_year(year):
  print("Year", year)
  if year % 4 == 0:
    if year % 100 == 0:
      if year % 400 == 0:
        return True
      else:
        return False
    else:
      return True
  else:
    return False

# check
print(is_leap_year(2020))
print(is_leap_year(2025))

Year 2020
True
Year 2025
False

In [9]:
# Exercise: 19: Print Alternate Prime Numbers till 20

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

n = 20
primes = []
for num in range(2, n + 1):
    if is_prime(num):
        primes.append(num)

print(f'All prime numbers from 1 to {n}: {primes}')

print(f'Alternate prime numbers from 1 to {n}:')

for i in range(0, len(primes), 2):
    print(primes[i])

All prime numbers from 1 to 20: [2, 3, 5, 7, 11, 13, 17, 19]
Alternate prime numbers from 1 to 20:
2
5
11
17

In [10]:
# Exercise 20: Print Reverse Number Pattern

def print_pattern(rows):
  for i in range(1, rows + 1):
    for j in range(rows - i + 1):
      print(i, end=" ")
    print()

print_pattern(5)

1 1 1 1 1
2 2 2 2
3 3 3
4 4
5

In [13]:
# Exercise 21: Check if a user-entered string contains any digits using a for loop

def contains_digits(text):
  for char in text:
    if '0' <= char <= '9':
      return True
  return False

# Get input from the user
user_string = input("Enter a string: ")

if contains_digits(user_string):
  print("The string contains at least one digit.")
else:
  print("The string does not contain any digits.")

Enter a string: Pynative123Python
The string contains at least one digit.

In [15]:
# Exercise 22: Capitalize the first letter of each word in a string

def capt_words(txt):
  ls = txt.split()
  ls = [word.capitalize() for word in ls]
  return " ".join(ls)

str1 = "pynative.com is for python lovers"

capitalized_string = capt_words(str1)
print("Capitalized string:", capitalized_string)

Capitalized string: Pynative.com Is For Python Lovers

In [16]:
# Exercise 23: Create a simple countdown timer using a while loop.
import time

def count_down(seconds):
  while seconds > 0:
    print(f"Time remaining: {seconds} seconds")
    time.sleep(1)
    seconds -= 1
  print("time's up")

count_down(10)

Time remaining: 10 seconds
Time remaining: 9 seconds
Time remaining: 8 seconds
Time remaining: 7 seconds
Time remaining: 6 seconds
Time remaining: 5 seconds
Time remaining: 4 seconds
Time remaining: 3 seconds
Time remaining: 2 seconds
Time remaining: 1 seconds
time's up