In [1]:
# Exercise 1: Write a program to accept two integer numbers from the user and calculate their product.

num1 = int(input("number 1: "))
num2 = int(input("number 2: "))

print(f"Multiplication: {num1 * num2}")

number 1: 4
number 2: 5
Multiplication: 20

In [2]:
# Exercise 2: Format Output String

str1 = 'My'
str2 = 'Name'
str3 = 'Is'
str4 = 'James'

print(str1, str2, str3, str4, sep= "**")

My**Name**Is**James

In [3]:
# Exercise 3: Display Decimal Number to Octal using print() function

num = 8
print('%o' % num)

10

In [5]:
# Exercise 4: Display Float Number with 2 Decimal Places

num = 458.541315
print(round(num, 2))

458.54

In [7]:
# Exercise 5: Accept a list of 5 float numbers as an input from the user

ls = []
for _ in range(0, 5):
  num = float(input("enter your number: "))
  ls.append(num)
print(ls)

enter your number: 1
enter your number: 5.5
enter your number: 69
enter your number: 5.3
enter your number: 6.9
[1.0, 5.5, 69.0, 5.3, 6.9]

In [9]:
# Exercise 6: Write all content of a file into a new file by skipping line number 5

with open('file.txt', 'r') as f:
  lines = f.readlines()

with open('new_file.txt', 'w') as f:
  count = 0
  for line in lines:
    if count == 4:
      count += 1
      continue
    else:
      f.write(line)
    count += 1

In [10]:
# Exercise 7: Accept any three string from one input() call

str1, str2, str3 = input("Enter three string: ").split()
print('Name1:', str1)
print('Name2:', str2)
print('Name3:', str3)

Enter three stringsam ali rick
Name1: sam
Name2: ali
Name3: rick

In [11]:
# Exercise 8: Format variables using string.format() method

totalMoney = 1000
quantity = 3
price = 450

print(f"I have {totalMoney} dollars so I can buy {quantity} football for {price} dollars.")

I have 1000 dollars so I can buy 3 football for 450 dollars.

In [ ]:
# Exercise 9: Check File is Empty or Not

import os

size = os.stat("test.txt").st_size
if size == 0:
    print('file is empty')

In [15]:
# Exercise 10: Read Line Number 4 from File

with open('file.txt', 'r') as f:
  lines = f.readlines()
  print(lines[3])

line4

In [16]:
# Exercise 11: Percentage Display

try:
  numb_1 = float(input("Enter the numerator: "))
  numb_2 = float(input("Enter the denominator: "))
  if numb_2 == 0:
    print("Error: Denominator cannot be zero.")
  else:
    res = (numb_1 / numb_2) * 100
    print(f"The percentage is: {res:.2f}%")
except ValueError:
    print("Invalid input. Please enter numbers.")

Enter the numerator: 25
Enter the denominator: 100
The percentage is: 25.00%

In [17]:
# Exercise 12: Interactive Menu

while True:
  print("\nMenu:")
  print("1. Say Hello")
  print("2. Calculate Square")
  print("3. Exit")

  choice = int(input("Enter your choice (1-3): "))

  if choice == 1:
    print('Hello')
  elif choice == 2:
    try:
      num = int(input('enter your number: '))
      res = num ** 2
      print(f"the square of {num} is {res}")
    except ValueError:
      print("Invalid input. Please enter an integer.")
  elif choice == 3:
    print('bye')
    break
  else:
    print("Invalid input")

Menu:
1. Say Hello
2. Calculate Square
3. Exit
Enter your choice (1-3): 7
Invalid input

Menu:
1. Say Hello
2. Calculate Square
3. Exit
Enter your choice (1-3): 2
enter your number: 5
the square of 5 is 25

Menu:
1. Say Hello
2. Calculate Square
3. Exit
Enter your choice (1-3): 1
Hello

Menu:
1. Say Hello
2. Calculate Square
3. Exit
Enter your choice (1-3): 3
bye

In [19]:
# Exercise 13: Display Right-Aligned Output

word = input("Enter a word: ")
number = input("Enter a number: ")
print(f"{word:>20}{number}")

Enter a word: sam
Enter a number: 20
                 sam20

In [21]:
# Exercise 14: Tabular Output from Lists

names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]

print(f"{'Name':<10} {'Score':<5}")
print("-" * 15)
for name, score in zip(names, scores):
    print(f"{name:<10} {score:<5}")

Name       Score
---------------
Alice      85
Bob        92
Charlie    78

In [23]:
# Exercise 15: Padding with Zeros

number_str = input("Enter a number: ")
padded_number = number_str.zfill(5)
print(padded_number)

Enter a number: 15
00015